
package ma.elhakki.proxy;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

import javax.naming.spi.ObjectFactory;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "BankWS", targetNamespace = "http://service.bankws.amarghad.ma/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BankWS {


    /**
     * 
     * @return
     *     returns java.util.List<ma.amarghad.proxy.Account>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAccounts", targetNamespace = "http://service.bankws.amarghad.ma/", className = "ma.amarghad.proxy.GetAccounts")
    @ResponseWrapper(localName = "getAccountsResponse", targetNamespace = "http://service.bankws.amarghad.ma/", className = "ma.amarghad.proxy.GetAccountsResponse")
    @Action(input = "http://service.bankws.amarghad.ma/BankWS/getAccountsRequest", output = "http://service.bankws.amarghad.ma/BankWS/getAccountsResponse")
    public List<Account> getAccounts();

    /**
     * 
     * @param arg0
     * @return
     *     returns ma.amarghad.proxy.Account
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAccount", targetNamespace = "http://service.bankws.amarghad.ma/", className = "ma.amarghad.proxy.GetAccount")
    @ResponseWrapper(localName = "getAccountResponse", targetNamespace = "http://service.bankws.amarghad.ma/", className = "ma.amarghad.proxy.GetAccountResponse")
    @Action(input = "http://service.bankws.amarghad.ma/BankWS/getAccountRequest", output = "http://service.bankws.amarghad.ma/BankWS/getAccountResponse")
    public Account getAccount(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param euroAmount
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "toMAD", targetNamespace = "http://service.bankws.amarghad.ma/", className = "ma.amarghad.proxy.ToMAD")
    @ResponseWrapper(localName = "toMADResponse", targetNamespace = "http://service.bankws.amarghad.ma/", className = "ma.amarghad.proxy.ToMADResponse")
    @Action(input = "http://service.bankws.amarghad.ma/BankWS/toMADRequest", output = "http://service.bankws.amarghad.ma/BankWS/toMADResponse")
    public double toMAD(
        @WebParam(name = "euroAmount", targetNamespace = "")
        double euroAmount);

}
